config/routes.rb
NewsReader::Application.routes.draw do
  root :to => "entries#index"

  devise_scope :users do
    root :to => "registrations#new"
  end

  resources :authentications

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
  controllers: {omniauth_callbacks: "authentications", registrations: "registrations"}

  resources :feeds
  resources :entries
  resources :users
  resources :facebook_posts, :only => [:create]
  resources :twitter_tweets, :only => [:create]
  resources :followers
  resources :news_feed_articles, :only => [:index, :create, :destroy, :update]
  resources :user_profiles, :only => [:index, :show]
  resources :following_articles, :only => [:index] 
  resources :reading_list_items, :only => [:index, :create, :destroy]
  resources :test_bookmarklets
  resources :reading_list_follower_entries, :only => [:index]
  resources :send_mails

end

app/models/entry.rb
class Entry < ActiveRecord::Base
  attr_accessible :post, :title, :description, :image, :provider_url, :url, :comment

  belongs_to :user
  belongs_to :feed 

  # validates :entry_id, :uniqueness => { scope => :user_id }
end
	

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
	before_filter :authenticate_user!

	def index 
		@entries = current_user.entries 
		respond_to do |format|
			format.json { render :json => @entries }
			format.html { render :index }
		end

	end 

	def create 
		entry = Entry.new(params[:entry])
		entry.user_id = current_user.id
		entry.save
		render :json => entry
	end 	

end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/index.html.erb
<div class="row-fluid">
  <div id= "navbar"></div>
  <div id="content"></div> 
</div>

  <%- User.omniauth_providers.each do |provider| %>
    <% unless current_user.authentications.map(&:provider).include?(provider.to_s) %> 
      <%= link_to "Connect your #{provider.to_s.titleize}", omniauth_authorize_path(current_user, provider) %><br />
    <% end %> 
  <% end -%>



<script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
<script type="text/javascript">


  $(function () {

    var entriesData = <%= current_user.entries.to_json.html_safe %>;
     var followingsData = <%= current_user.followings.to_json.html_safe %>; 
     var articlesData = <%= current_user.news_feed_articles.to_json.html_safe %>;
     var readingListData = <%= current_user.reading_list_items.to_json.html_safe %> 
    // var followingsData = {};
    
    window.username =  "<%= current_user.name %>";
    window.email = "<%= current_user.email %>";

    window.FR.initialize(
      $("#content"),
      entriesData,
      followingsData,
      articlesData,
      readingListData,
      $("#navbar"),
      "<%= current_user.name %>"
    );
    window.user_id = <%= current_user.id %>;
  });

</script>